language: php

matrix:
  fast_finish: true
  include:
    - env: DBTYPE=sqlite LANG=en MW=master WB=both
      php: hhvm-nightly

before_script:
    - bash ./build/travis/install.sh
    - bash ./build/travis/mw-apply-wb-settings.sh
    - bash ./build/travis/update-db.sh

script:
    - bash ./build/travis/script.sh
